### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by Robert-khayreev**

### CODE REVIEW

**Comment by FZambia** [comment]
@Robert-khayreev hello, thanks! Could you please also bump a version of chart - this is strange since the change in readme but required for workflow at the moment.

**Comment by Robert-khayreev** [comment]
> @Robert-khayreev hello, thanks! Could you please also bump a version of chart - this is strange since the change in readme but required for workflow at the moment.
Done

**Comment by FZambia** [comment]
Unfortunate, seems like we also have to update kind action to v1.2.0 instead of v1.0.0 in test workflow - https://github.com/helm/kind-action/issues/42 - sorry for that,  can you please commit this change too? On this line https://github.com/centrifugal/helm-charts/blob/master/.github/workflows/lint-test.yaml#L23

**Comment by FZambia** [comment]
Just did this myself - thanks again :)

**Pull request merged**
