### PR TITLE
ingressInternal

### PR DESCRIPTION
**Pull request by bkomraz1**
Signed-off-by: Boris Komraz <bkomraz1@gmail.com>

### CODE REVIEW

**Comment by bkomraz1** [comment]
@FZambia Can you review the pull request please?

**Comment by bkomraz1** [comment]
@FZambia,  I expose service port by public ingress for our customers through public load balancer that world wide available. But administrative console that are available on port 9000 I do not want to expose by public load balancer. Instead of it I want to expose it by by another ingress class that is bind to load balancer available from limited address range.

**Comment by FZambia** [comment]
So `admin_external` option which allows running admin web UI on public port does not fit your case right? Probably it's still possible to use that option and limit access to admin UI by configuring IP restrictions for admin endpoints on existing ingress.

I am asking because when exporting the entire internal service you also export Prometheus metrics endpoint and API endpoint - I don't think it's desired?

**Comment by bkomraz1** [comment]
> So admin_external option which allows running admin web UI on public port does not fit your case right? Probably it's still possible to use that option and limit access to admin UI by configuring IP restrictions for admin endpoints on existing ingress.

I am limiting IP range on LB level (AWS nlb). So it is impossible for me use the same load balancer and distinguish IP ranges.

> I am asking because when exporting the entire internal service you also export Prometheus metrics endpoint and API endpoint - I don't think it's desired?

It is not problem for me, because I allow access to internal port from limited IP range, not world wide. Users that would want to limit access to internal port can do it by adding correspondent annotations.

Unfortunate internal port exposes some independent endpoints and UI  located at root that makes configuration awkward.

**Comment by FZambia** [comment]
Theoretically you can configure the path from which Centrifugo serves admin UI endpoints using admin_handler_prefix option to sth like `/admin`, see https://centrifugal.dev/docs/server/configuration#customize-handler-endpoints. Will this help to make the configuration less awkward?

**Comment by bkomraz1** [comment]
Using `admin_handler_prefix` like `/ui` (and not as `/admin`, because `/admin` is reserved for api ) is a good idea I may create pull request for it. But it is breaking changes and requires documentation update.

In any case port 9000 should be exposed by separate ingress like ingressInternal. The truth is that it will be possible to expose ui only (without exposing other internal endpoints).

**Comment by FZambia** [comment]
> Using admin_handler_prefix like /ui (and not as /admin, because /admin is reserved for api ) is a good idea I may create pull request for it. But it is breaking changes and requires documentation update.

Not sure I understood this, I meant you can only change the `admin_handler_prefix` for your own setup. Or I am missing sth?

> In any case port 9000 should be exposed by separate ingress like ingressInternal. The truth is that it will be possible to expose ui only (without exposing other internal endpoints).

Could you please add a comment which warns about exposing internal endpoints to `charts/centrifugo/values.yaml` for `ingressInternal` section?

**Comment by bkomraz1** [comment]
> Could you please add a comment which warns about exposing internal endpoints to charts/centrifugo/values.yaml for ingressInternal section?

Done: https://github.com/centrifugal/helm-charts/pull/42/commits/7e21e75a91ebcee1d6d4ef9c3c955378d2ffcc99

**Comment by FZambia** [comment]
Thanks!

**Pull request merged**
